#!/bin/bash

# ReverseQR Service Setup Script
# This script generates and installs the systemd service file dynamically

set -e

# Ensure output is not buffered
export PYTHONUNBUFFERED=1

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_NAME="reverseqr"
SERVICE_FILE="/tmp/${SERVICE_NAME}.service"

echo "Detecting system configuration..." >&2

# Get the current user
CURRENT_USER="${SUDO_USER:-$(whoami)}"
echo "[DEBUG] Current user: $CURRENT_USER" >&2

# Find the node executable
echo "[DEBUG] Searching for node executable..." >&2
NODE_PATH=$(which node 2>&1) || true
if [ -z "$NODE_PATH" ]; then
  echo "ERROR: node executable not found in PATH" >&2
  echo "Please install Node.js or ensure it's in your PATH" >&2
  exit 1
fi

echo "=== ReverseQR Service Setup ===" >&2
echo "Installation directory: $SCRIPT_DIR" >&2
echo "User: $CURRENT_USER" >&2
echo "Node executable: $NODE_PATH" >&2
echo "" >&2

# Generate the service file
echo "[DEBUG] Generating service file at $SERVICE_FILE" >&2
cat > "$SERVICE_FILE" << EOF
# ReverseQR systemd service file
# Generated by setup-service.sh on $(date)
# Installation directory: $SCRIPT_DIR

[Unit]
Description=ReverseQR - Secure File Sharing Server
After=network.target

[Service]
Type=simple
User=$CURRENT_USER
WorkingDirectory=$SCRIPT_DIR

# Environment variables (loaded from .env file)
EnvironmentFile=$SCRIPT_DIR/.env

# Start command
ExecStart=$NODE_PATH $SCRIPT_DIR/src/server.js

# Restart policy
Restart=on-failure
RestartSec=10

# Process management
StandardOutput=journal
StandardError=journal
SyslogIdentifier=$SERVICE_NAME

# Security settings
PrivateTmp=true
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF

echo "[DEBUG] Service file generated successfully at $SERVICE_FILE" >&2
echo "" >&2

# Check if running with sudo
if [[ $EUID -ne 0 ]]; then
   echo "This script needs sudo to install the service file." >&2
   echo "" >&2
   echo "To install the service, run:" >&2
   echo "  sudo bash $0" >&2
   echo "" >&2
   echo "Or manually install with:" >&2
   echo "  sudo cp $SERVICE_FILE /etc/systemd/system/${SERVICE_NAME}.service" >&2
   echo "  sudo systemctl daemon-reload" >&2
   echo "  sudo systemctl enable ${SERVICE_NAME}" >&2
   echo "  sudo systemctl start ${SERVICE_NAME}" >&2
   exit 0
fi

# Install the service file
echo "[*] Installing service file to /etc/systemd/system/${SERVICE_NAME}.service..." >&2
cp -v "$SERVICE_FILE" "/etc/systemd/system/${SERVICE_NAME}.service" >&2

# Reload systemd daemon
echo "[*] Reloading systemd daemon..." >&2
systemctl daemon-reload >&2

# Enable the service
echo "[*] Enabling ${SERVICE_NAME} service to start on boot..." >&2
systemctl enable "${SERVICE_NAME}" >&2

# Start the service
echo "[*] Starting ${SERVICE_NAME} service..." >&2
systemctl start "${SERVICE_NAME}" >&2

echo "" >&2
echo "=== Installation Complete ===" >&2
echo "" >&2
echo "Service management commands:" >&2
echo "  sudo systemctl status ${SERVICE_NAME}       # Check status"
echo "  sudo systemctl start ${SERVICE_NAME}        # Start service"
echo "  sudo systemctl stop ${SERVICE_NAME}         # Stop service"
echo "  sudo systemctl restart ${SERVICE_NAME}      # Restart service"
echo "  sudo systemctl disable ${SERVICE_NAME}      # Disable auto-start"
echo "  sudo journalctl -u ${SERVICE_NAME} -f       # View live logs"
echo ""
