#!/bin/bash

# ReverseQR Service Setup Script
# This script generates and installs the systemd service file dynamically

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_NAME="reverseqr"
SERVICE_FILE="/tmp/${SERVICE_NAME}.service"

# Get the current user
CURRENT_USER="${SUDO_USER:-$(whoami)}"

echo "=== ReverseQR Service Setup ==="
echo "Installation directory: $SCRIPT_DIR"
echo "User: $CURRENT_USER"
echo ""

# Generate the service file
cat > "$SERVICE_FILE" << EOF
# ReverseQR systemd service file
# Generated by setup-service.sh on $(date)
# Installation directory: $SCRIPT_DIR

[Unit]
Description=ReverseQR - Secure File Sharing Server
After=network.target

[Service]
Type=simple
User=$CURRENT_USER
WorkingDirectory=$SCRIPT_DIR

# Environment variables (loaded from .env file)
EnvironmentFile=$SCRIPT_DIR/.env

# Start command
ExecStart=/usr/bin/node $SCRIPT_DIR/src/server.js

# Restart policy
Restart=on-failure
RestartSec=10

# Process management
StandardOutput=journal
StandardError=journal
SyslogIdentifier=$SERVICE_NAME

# Security settings
PrivateTmp=true
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF

echo "Generated service file: $SERVICE_FILE"
echo ""

# Check if running with sudo
if [[ $EUID -ne 0 ]]; then
   echo "This script needs sudo to install the service file."
   echo ""
   echo "To install the service, run:"
   echo "  sudo bash $0"
   echo ""
   echo "Or manually install with:"
   echo "  sudo cp $SERVICE_FILE /etc/systemd/system/${SERVICE_NAME}.service"
   echo "  sudo systemctl daemon-reload"
   echo "  sudo systemctl enable ${SERVICE_NAME}"
   echo "  sudo systemctl start ${SERVICE_NAME}"
   exit 0
fi

# Install the service file
echo "Installing service file to /etc/systemd/system/${SERVICE_NAME}.service..."
cp "$SERVICE_FILE" "/etc/systemd/system/${SERVICE_NAME}.service"

# Reload systemd daemon
echo "Reloading systemd daemon..."
systemctl daemon-reload

# Enable the service
echo "Enabling ${SERVICE_NAME} service to start on boot..."
systemctl enable "${SERVICE_NAME}"

# Start the service
echo "Starting ${SERVICE_NAME} service..."
systemctl start "${SERVICE_NAME}"

echo ""
echo "=== Installation Complete ==="
echo ""
echo "Service management commands:"
echo "  sudo systemctl status ${SERVICE_NAME}       # Check status"
echo "  sudo systemctl start ${SERVICE_NAME}        # Start service"
echo "  sudo systemctl stop ${SERVICE_NAME}         # Stop service"
echo "  sudo systemctl restart ${SERVICE_NAME}      # Restart service"
echo "  sudo systemctl disable ${SERVICE_NAME}      # Disable auto-start"
echo "  sudo journalctl -u ${SERVICE_NAME} -f       # View live logs"
echo ""
