// Simplified PGP Wordlist - Single short, memorable word per hex byte
const pgpWordlist = {
  "00": "aardvark",
  "01": "absurd",
  "02": "aftermath",
  "03": "acme",
  "04": "adrift",
  "05": "adult",
  "06": "amulet",
  "07": "ahead",
  "08": "antenna",
  "09": "applicant",
  "0A": "allow",
  "0B": "alone",
  "0C": "ammo",
  "0D": "asteroid",
  "0E": "apple",
  "0F": "artist",
  "10": "assume",
  "11": "Athens",
  "12": "atlas",
  "13": "Aztec",
  "14": "baboon",
  "15": "backfield",
  "16": "bodyguard",
  "17": "banjo",
  "18": "beaming",
  "19": "bedlamp",
  "1A": "beehive",
  "1B": "beeswax",
  "1C": "befriend",
  "1D": "Belfast",
  "1E": "berserk",
  "1F": "billiard",
  "20": "bison",
  "21": "blackjack",
  "22": "blockade",
  "23": "cannonball",
  "24": "bluebird",
  "25": "caravan",
  "26": "bookshelf",
  "27": "celebrate",
  "28": "breadline",
  "29": "breakup",
  "2A": "brickyard",
  "2B": "Cherokee",
  "2C": "Chicago",
  "2D": "button",
  "2E": "buzzard",
  "2F": "cement",
  "30": "commando",
  "31": "company",
  "32": "checkup",
  "33": "chisel",
  "34": "choking",
  "35": "chopper",
  "36": "Christmas",
  "37": "clamshell",
  "38": "classic",
  "39": "classroom",
  "3A": "cleanup",
  "3B": "clockwork",
  "3C": "cobra",
  "3D": "crucifix",
  "3E": "concert",
  "3F": "cowbell",
  "40": "Dakota",
  "41": "cranky",
  "42": "December",
  "43": "decimal",
  "44": "crumpled",
  "45": "detector",
  "46": "cubic",
  "47": "dashboard",
  "48": "deadbolt",
  "49": "dinosaur",
  "4A": "dogsled",
  "4B": "dragnet",
  "4C": "drainage",
  "4D": "dreadful",
  "4E": "drifter",
  "4F": "document",
  "50": "drumbeat",
  "51": "enchanting",
  "52": "enrollment",
  "53": "dwelling",
  "54": "eating",
  "55": "edict",
  "56": "escapade",
  "57": "eightball",
  "58": "everyday",
  "59": "examine",
  "5A": "enlist",
  "5B": "exodus",
  "5C": "escape",
  "5D": "filament",
  "5E": "finicky",
  "5F": "forever",
  "60": "fortitude",
  "61": "fallout",
  "62": "gadgetry",
  "63": "flatfoot",
  "64": "getaway",
  "65": "fracture",
  "66": "gossamer",
  "67": "freedom",
  "68": "gravity",
  "69": "gazelle",
  "6A": "hamburger",
  "6B": "glitter",
  "6C": "handiwork",
  "6D": "goggles",
  "6E": "goldfish",
  "6F": "gremlin",
  "70": "guidance",
  "71": "hideaway",
  "72": "holiness",
  "73": "hurricane",
  "74": "indoors",
  "75": "indulge",
  "76": "impetus",
  "77": "inception",
  "78": "indigo",
  "79": "jawbone",
  "7A": "keyboard",
  "7B": "inferno",
  "7C": "kiwi",
  "7D": "klaxon",
  "7E": "locale",
  "7F": "lockup",
  "80": "merit",
  "81": "minnow",
  "82": "Istanbul",
  "83": "Jamaica",
  "84": "Jupiter",
  "85": "music",
  "86": "necklace",
  "87": "liberty",
  "88": "maritime",
  "89": "matchmaker",
  "8A": "maverick",
  "8B": "Medusa",
  "8C": "megaton",
  "8D": "microscope",
  "8E": "orca",
  "8F": "midsummer",
  "90": "peachy",
  "91": "miracle",
  "92": "physique",
  "93": "molasses",
  "94": "Pluto",
  "95": "Montana",
  "96": "monument",
  "97": "mosquito",
  "98": "printer",
  "99": "nebula",
  "9A": "pupil",
  "9B": "puppy",
  "9C": "python",
  "9D": "Ohio",
  "9E": "quiver",
  "9F": "quota",
  "A0": "ragtime",
  "A1": "ratchet",
  "A2": "Pacific",
  "A3": "reform",
  "A4": "Pandora",
  "A5": "reindeer",
  "A6": "rematch",
  "A7": "repay",
  "A8": "retouch",
  "A9": "revenge",
  "AA": "reward",
  "AB": "Pegasus",
  "AC": "ribcage",
  "AD": "ringbolt",
  "AE": "robust",
  "AF": "rocker",
  "B0": "ruffled",
  "B1": "sailboat",
  "B2": "pioneer",
  "B3": "scallion",
  "B4": "scenic",
  "B5": "positive",
  "B6": "potato",
  "B7": "seabird",
  "B8": "select",
  "B9": "sentence",
  "BA": "shadow",
  "BB": "shamrock",
  "BC": "pyramid",
  "BD": "quantity",
  "BE": "skydive",
  "BF": "slingshot",
  "C0": "recipe",
  "C1": "recover",
  "C2": "snapshot",
  "C3": "replica",
  "C4": "snowslide",
  "C5": "solo",
  "C6": "southward",
  "C7": "soybean",
  "C8": "spaniel",
  "C9": "spearhead",
  "CA": "revenue",
  "CB": "revival",
  "CC": "revolver",
  "CD": "sandalwood",
  "CE": "spyglass",
  "CF": "Saturday",
  "D0": "savagery",
  "D1": "stairway",
  "D2": "sensation",
  "D3": "stapler",
  "D4": "steamship",
  "D5": "sterling",
  "D6": "speculate",
  "D7": "stopwatch",
  "D8": "stormy",
  "D9": "sugar",
  "DA": "surrender",
  "DB": "suspicious",
  "DC": "sympathy",
  "DD": "tambourine",
  "DE": "telephone",
  "DF": "talon",
  "E0": "tobacco",
  "E1": "tolerance",
  "E2": "tiger",
  "E3": "torpedo",
  "E4": "tradition",
  "E5": "topmost",
  "E6": "tracker",
  "E7": "transit",
  "E8": "typewriter",
  "E9": "ultimate",
  "EA": "Trojan",
  "EB": "underfoot",
  "EC": "unicorn",
  "ED": "tunnel",
  "EE": "universe",
  "EF": "uncut",
  "F0": "unearth",
  "F1": "unwind",
  "F2": "vagabond",
  "F3": "upset",
  "F4": "upshot",
  "F5": "visitor",
  "F6": "vocalist",
  "F7": "voyager",
  "F8": "Vulcan",
  "F9": "waffle",
  "FA": "whimsical",
  "FB": "watchword",
  "FC": "wayside",
  "FD": "willow",
  "FE": "woodlark",
  "FF": "Zulu"
};

/**
 * Encode bytes to PGP words using simplified word list
 * @param {Buffer} data - Data to encode
 * @returns {string} PGP word string (space-separated)
 */
function encodeToPgp(data) {
  if (!data || data.length === 0) return '';
  const words = [];
  for (let i = 0; i < data.length; i++) {
    const byte = data[i];
    const hex = byte.toString(16).toUpperCase().padStart(2, '0');
    const word = pgpWordlist[hex];
    
    if (!word) {
      throw new Error(`Invalid wordlist entry for byte ${hex}: word not found`);
    }
    
    words.push(word);
  }
  return words.join(' ');
}

/**
 * Decode PGP words back to bytes using simplified word list
 * @param {string} encoded - Space or dash separated PGP words
 * @returns {Buffer} Decoded data
 * @throws {Error} If a word is unknown
 */
function decodeFromPgp(encoded) {
  if (!encoded) return Buffer.from([]);
  
  const words = encoded.toLowerCase().split(/[\s-]+/).filter(w => w);
  const bytes = [];
  
  // Create reverse lookup: word -> hex byte
  const wordToHex = {};
  for (const [hex, word] of Object.entries(pgpWordlist)) {
    wordToHex[word.toLowerCase()] = hex;
  }
  
  for (let i = 0; i < words.length; i++) {
    const word = words[i];
    const hex = wordToHex[word];
    
    if (hex === undefined) {
      throw new Error(`Unknown PGP word: "${word}" at position ${i}. Word was forgotten or mistyped.`);
    }
    
    bytes.push(parseInt(hex, 16));
  }
  
  return Buffer.from(bytes);
}

module.exports = { encodeToPgp, decodeFromPgp, pgpWordlist };
